export const REGIONS = [
  { label: "서울", value: "서울", ratio: 7, numberOfApplicants: 4 },
  { label: "광주", value: "광주", ratio: 4, numberOfApplicants: 2 },
  { label: "울산", value: "울산", ratio: 3, numberOfApplicants: 1 },
  { label: "경기", value: "경기", ratio: 28, numberOfApplicants: 14 },
  { label: "충북", value: "충북", ratio: 4, numberOfApplicants: 2 },
  { label: "전북", value: "전북", ratio: 5, numberOfApplicants: 2 },
  { label: "부산", value: "부산", ratio: 5, numberOfApplicants: 3 },
  { label: "대구", value: "대구", ratio: 4, numberOfApplicants: 2 },
  { label: "인천", value: "인천", ratio: 6, numberOfApplicants: 3 },
  { label: "대전", value: "대전", ratio: 3, numberOfApplicants: 1 },
  { label: "강원", value: "강원", ratio: 4, numberOfApplicants: 2 },
  { label: "충남(세종)", value: "충남(세종)", ratio: 6, numberOfApplicants: 3 },
  { label: "전남", value: "전남", ratio: 5, numberOfApplicants: 3 },
  { label: "경북", value: "경북", ratio: 6, numberOfApplicants: 3 },
  { label: "경남", value: "경남", ratio: 8, numberOfApplicants: 4 },
  { label: "제주", value: "제주", ratio: 1, numberOfApplicants: 1 },
];
