/* eslint-disable @typescript-eslint/no-explicit-any */
export interface Worker {
  _id: string;
  email: string;
  password: string;
  name: string;
  phoneNumber: string;
  alternativePhoneNumber: string;
  age: number;
  address: string;
  country: string;
  photoRegistration: string;
  graduationCertificate: string;
  qualification: string;
  sessionToken: string;
  refreshToken: string;
  isVerified: boolean;
  createdAt: string;
  cv: string | null;
  height: number | null;
  weight: number | null;
  religion: string | null;
  marital: "single" | "married" | "divorced" | "widowed" | null;
  shoeSize: number | null;
  bloodGroup: string | null;
  relationship: string | null;
  relPhoneNumber: string | null;
  relFullName: string | null;
  relDateOfBirth: string | null;
  collegeName: string | null;
  collageMajor: string | null;
  collageStartDate: string | null;
  collageGraduationDate: string | null;
  allergies: string | null;
  typeOfPropertyOwned: string | null;
  dietInformation: string | null;
  remarried: boolean | null;
  universities: string | null;
  foreignExperiences: string | null;
  languageProficiencies: string | null | any[];
  professionalCertificates: string | null;
  workplaceInformation: {
    companyName: string;
    startDate: string;
    workingPeriod: string;
    field: string;
    position: string;
    file: string;
  }[];
  interviewVideo: string | null;
  skillsVerificationVideo: string | null;
  experienceVideo: string | null;
  dateOfBirth: string | null;
  gender: string;
}
