export interface Worker {
  id: number;
  email: string;
  password: string;
  name: string;
  phoneNumber: string;
  alternativePhoneNumber: string;
  age: number;
  gender: 'male' | 'female' | 'other';
  address: string;
  country: string;
  photoRegistration: string;
  graduationCertificate: string;
  qualification: string;
  sessionToken: string;
  refreshToken: string;
  isVerified: boolean;
  createdAt: string;
  cv: string | null;
  height: number | null;
  weight: number | null;
  religion: string | null;
  marital: 'single' | 'married' | 'divorced' | 'widowed' | null;
  shoeSize: number | null;
  bloodGroup: string | null;
  relationship: string | null;
  relPhoneNumber: string | null;
  relFullName: string | null;
  relDateOfBirth: string | null;
  collegeName: string | null;
  collageMajor: string | null;
  collageStartDate: string | null;
  collageGraduationDate: string | null;
  allergies: string | null;
  typeOfPropertyOwned: string | null;
  dietInformation: string | null;
  remarried: boolean | null;
  universities: string | null;
  foreignExperiences: string | null;
  languageProficiencies: string | null;
  professionalCertificates: string | null;
  workplaceInformation: string | null;
  interviewVideo: string | null;
  skillsVerificationVideo: string | null;
  experienceVideo: string | null;
}
